apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notify-frame-flow
  name: notify-frame-flow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: notify-frame-flow
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notify-frame-flow
    spec:
      containers:
        - name: notify-frame-flow
          image: 090111931170.dkr.ecr.us-east-1.amazonaws.com/frameflow-ecr
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: SQS_QUEUE
              valueFrom:
                secretKeyRef:
                  name: notify-secret-frameflow
                  key: SQS_QUEUE
            - name: S3_BUCKET_ZIP
              valueFrom:
                secretKeyRef:
                  name: notify-secret-frameflow
                  key: S3_BUCKET_ZIP
            - name: SMTP_EMAIL
              valueFrom:
                secretKeyRef:
                  name: notify-secret-frameflow
                  key: SMTP_EMAIL
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notify-secret-frameflow
                  key: SMTP_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: notify-secret-frameflow
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: notify-secret-frameflow
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: notify-secret-frameflow
                  key: AWS_SESSION_TOKEN
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: notify-secret-frameflow
                  key: AWS_REGION
          livenessProbe:
            httpGet:
              path: /manage/health
              port: 80
              httpHeaders:
                - name: Custom-Header
                  value: Awesome
            initialDelaySeconds: 100
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /manage/health
              port: 80
            initialDelaySeconds: 100
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
