apiVersion: v1
kind: Service
metadata:
  labels:
    app: notify-frame-flow
  name: notify-frame-flow
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30790
    port: 80
    protocol: TCP
    targetPort: 8787
  selector:
    app: notify-frame-flow
  sessionAffinity: None