
services:
  web:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    image: notify-frame-flow
    container_name: notify-frame-flow
    restart: always
    ports:
      - "80:8787"
    networks:
      - sql_network
    environment:
      - SQS_QUEUE=${SQS_QUEUE}
      - S3_BUCKET_ZIP=${S3_BUCKET_ZIP}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION}
networks:
  sql_network:
    driver: bridge